apiVersion: apps/v1
kind: Deployment
metadata:
  name: gts-website
  namespace: gts
  labels:
    app: gts-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gts-website
  template:
    metadata:
      labels:
        app: gts-website
    spec:
      containers:
      - name: gts-website
        image: registry.glidingthrough.space/gts-website:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
